---
- hosts: vmcreate-Ubuntu
  gather_facts: false
  connection: local
  vars:
    - vcenter_hostname: ''  #defined in group_vars/all/configs
    - vcenter_user: ''  #defined in group_vars/all/accounts
    - vcenter_pass: ''  #defined in group_vars/all/accounts
    - datacenter: ''  #defined in group_vars/all/configs
    - esxi_host: ''  #defined in group_vars/all/configs
    - vcenter_resource_pool: ''  #defined in group_vars/all/configs
    - vcenter_cluster: ''  #defined in group_vars/all/configs
    - vm_state: present
    - notes: Created by Ansible
- include: "gather_vm_details.yml"
