---
# install apt key
- apt_key: url=https://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

# logstash repository
- apt_repository: repo='deb http://packages.elasticsearch.org/logstash/{{logstash_version}}/debian stable main' state=present

# install logstash and java
- name: install logstash and java
  apt: name={{ item }} state=latest force=yes
  with_items:
    - logstash
#    - logstash-contrib
    - openjdk-7-jre-headless
  notify: init logstash

# disable logstash-web
- name: checking for logstash-web
  stat: path=/etc/init/logstash-web.conf
  register: logstash_web
- name: disable logstash-web
  replace: dest=/etc/init/logstash-web.conf regexp='^start on virtual-filesystems' replace='start on never' backup=yes
  notify: stop logstash-web
  when: logstash_web.stat.exists
