---

# Ensure ferm is installed (Debian)
- name: ensuring ferm is installed
  apt: name=ferm state=present
  when: ansible_os_family == "Debian"

- name: ensuring ferm is installed (RedHat)
  yum: name=ferm state=present
  when: ansible_os_family == "RedHat"

# Ensure ferm is started and enabled
- name: ensuring ferm is started and enabled
  service: name=ferm state=started enabled=yes

- name: ferm | config | uploading firewall rules
  template: src=etc/ferm/ferm.d/20-quagga.conf.j2 dest=/etc/ferm/ferm.d/20-quagga.conf owner=root group=root mode=0700
  notify: run ferm
