---
- hosts: graylog-servers
  remote_user: remote
  sudo: yes
  roles:
    - { role: disable-firewall, when: not enable_firewall }
    - { role: enable-firewall, when: enable_firewall }
    - base
    - collectd
    - { role: snmpd, when: enable_snmpd }
    - { role: timezone, when: change_timezone }
    - { role: zabbix-agent, when: enable_zabbix_monitoring }
    - elasticsearch
    - mongodb
    - graylog
