---
- hosts: all
  sudo: yes
  remote_user: remote
  roles:
    - { role: disable-firewall, when: not enable_firewall }
    - { role: enable-firewall, when: enable_firewall }
    - { role: change-hostname, when: update_hostname }
    - { role: snmpd, when: enable_snmpd }
    - { role: timezone, when: change_timezone }
    - { role: zabbix-agent, when: enable_zabbix_monitoring }
    - { role: collectd, when: enable_collectd_monitoring }
