---
- hosts: ip-services
  remote_user: remote
  sudo: yes
  roles:
    - mariadb-galera-cluster
    - apache2

- hosts: nameservers
  remote_user: remote
  sudo: yes
  roles:
    - { role: powerdns, when: install_dns }
    - { role: isc-dhcp, when: install_dhcp }
    - { role: phpipam, when: install_phpipam }
