---
hosts:
  - name: example
    create: true
    groups:
      - example-server
    vars:
      - name: example_var
        value: example_value
        set: true
  - name: ns1
    create: true
    groups:
      - ubuntu-servers
      - nameservers
    vars:
      - name: a_var
        value: c_value
        set: false
      - name: b_var
        value: d_value
        set: false
  - name: ns2
    create: true
    groups:
      - ubuntu-servers
      - nameservers
    vars: []
  - name: Homeserv
    create: true
    groups:
      - windows-servers
    vars: []
