---
# tasks file for ansible-hashicorp-toolbelt
- include_tasks: debian.yml
  when: >
        ansible_os_family == "Debian" and
        hashicorp_tools != []

- include_tasks: install.yml
  when: hashicorp_tools != []
