galaxy_info:
  author: Larry Smith Jr.
  description: your description

  license: MIT

  min_ansible_version: 1.2

  platforms:
    - name: EL
      versions:
        - 7
    - name: Ubuntu
      versions:
        - xenial

  galaxy_tags:
    - automation

dependencies: []
