---
- name: redhat | installing pre-reqs
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - 'MySQL-python'
  when: ansible_distribution_release != "Fedora"

- name: centos | installing mysql CentOS 6
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql
  when: >
        ansible_distribution_release != "Fedora" and
        (ansible_distribution_version < '7')

- name: centos | enabling on boot and start CentOS 6
  service:
    name: mysqld
    state: started
    enabled: yes
  when: (ansible_distribution_version < '7')

- name: centos | installing mariadb mysql CentOS 7
  yum:
    name: "{{ item }}"
    state: present
  register: mariadb_server_installed
  with_items:
    - mariadb-server
    - mariadb
  when: >
        ansible_distribution_release != "Fedora" and
        (ansible_distribution_version >= '7')

- name: centos | enabling on boot and start CentOS 7
  service:
    name: mariadb
    state: started
    enabled: yes
  when: (ansible_distribution_version >= '7')
