---
- name: debian | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - debian-archive-keyring
    - apt-transport-https

- name: debian | Adding GitLab Runner GPG Key
  apt_key:
    url: "{{ gitlab_runner_debian_package['key'] }}"
    state: present
  become: true

- name: debian | Adding GitLab Repo(s)
  apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  with_items: "{{ gitlab_runner_debian_package['repos'] }}"

- name: debian | Pinning GitLab Repo
  template:
    src: etc/apt/preferences.d/pin-gitlab-runner.pref.j2
    dest: /etc/apt/preferences.d/pin-gitlab-runner.pref
  become: true

- name: debian | Installing GitLab Runner Package
  apt:
    name: "gitlab-ci-multi-runner={{ gitlab_runner_version }}"
    state: present
  become: true
