---
# handlers file for ansible-squid
- name: restart squid
  service:
    name: "squid"
    state: "restarted"

- name: restart squid3
  service:
    name: "squid3"
    state: "restarted"

- name: reload haproxy
  service:
    name: "haproxy"
    state: "reloaded"

- name: restart haproxy
  service:
    name: "haproxy"
    state: "restarted"

- name: reload ferm
  shell: service ferm force-reload
