---
galaxy_info:
  author: Larry Smith Jr.
  description: An [Ansible] role to install [KVM]

  license: license (MIT)
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  - name: Ubuntu
    versions:
    - trusty
    - xenial
    - yakkety
    - zesty
  - name: Debian
    versions:
    - jessie

  categories:
  - cloud
  - networking
  - system
dependencies: []
