---
- name: ensuring ferm is installed
  apt: name=ferm state=present
  when: ansible_os_family == "Debian"

- name: ensuring ferm is installed (RedHat)
  yum: name=ferm state=present
  when: ansible_os_family == "RedHat"

- name: ensuring ferm is started and enabled
  service: name=ferm state=started enabled=yes

- name: ferm | configuring firewall
  template: src=ferm.d/20-keepalived.conf.j2 dest=/etc/ferm/ferm.d/20-keepalived.conf owner=root group=root mode=0700
  notify: run ferm
