---
# Open firewall ports
- include: ferm.yml
  tags: [ferm]
  when: enable_firewall

- include: debian_keepalived.yml
  when: ansible_os_family == "Debian"

- include: centos_keepalived.yml
  when: ansible_os_family == "RedHat"

- include: config_keepalived.yml
  tags: [config_keepalived]
  when: config_keepalived

- include: config_conntrackd.yml
  when: enable_conntrackd and config_conntrackd
