---
- name: debian | adding mongodb repo key
  apt_key:
    keyserver: "{{ mongodb_apt_keyserver }}"
    id: "{{ mongodb_apt_gpg_key }}"
    state: present

- name: debian | adding mongodb apt repo
  apt_repository:
    repo: "{{ mongodb_apt_repo }}"
    state: present

- name: debian | installing mongodb
  apt:
    name: mongodb-org
    state: present
